from __future__ import annotations

TARGET_SFREQ = 200.0
SAMPLE_ID_STR_DTYPE = "<U128"
SUBJECT_ID_STR_DTYPE = "<U64"

QC_SHORT_PADDED = 1
QC_NAN_INF_REPLACED = 2
QC_HIGH_AMPLITUDE = 4
QC_FLAT_CHANNEL = 8
QC_LOW_CHANNEL_COUNT = 16
QC_MISSING_CHANNEL_NAME = 32
QC_SOURCE_ARTIFACT = 64
QC_EVENT_CLIPPED = 128

HIGH_AMPLITUDE_UV = 500.0
FLAT_STD_UV = 1e-6
