  split_mode: stratified_random
  train_ratio: 0.8
  val_ratio: 0.1
  select_metric: F1
  use_gpu: true
  train_epochs: 10
  patience: 3
  batch_size: 32
  learning_rate: 0.0001
  lradj: cosine
  n_heads: 8
  t_layer: 6
  v_layer: 6
  dropout: 0.0
  patch_len: 1
  patch_stride: None
  augmentations: none
  channel_basis_dim: 32
  k_basis_dim: 16
  t_basis_dim: 16
  patch_embed_dim: 128
