#!/bin/bash
#BSUB -J tridim_apava
#BSUB -q gpu-bme-liuqy
#BSUB -n 4
#BSUB -gpu "num=1"
#BSUB -R "span[ptile=4]"
#BSUB -e /work/bme-susy/TriDim_model/logs/%J.err
#BSUB -o /work/bme-susy/TriDim_model/logs/%J.out

set -e
cd ~/xinke/TriDim_small
mkdir -p logs

module load python/anaconda3/2022.10
source /share/apps/anaconda3/etc/profile.d/conda.sh
conda activate /work/bme-susy/.conda/envs/tridim

python run.py \
    --model eeg_mixer_v3_tconv \
    --data APAVA \
    --dataset_paths_yaml ./configs/datasets/APAVA.yaml \
    --itr 5 \
    --seed_start 42 \
    --gpu 2 \
    --gpu_idx 2 \
    2>&1 | tee logs/${LSB_JOBID}_APAVA_eeg_mixer_v3_tconv.train.log
