dataset: FACED_new
root_path: /work/bme-shenxk/data/FACED_new
params:
  seq_len: 2000
  input_channel_coord_path: ./configs/electrodes/FACED_new.csv
  model: eeg_mixer_v3_tconv
  itr: 5
  seed_start: 42
  split_mode: label_order
  select_metric: F1
  use_gpu: true
  gpu_idx:
  - 0
  gpu: 0
  num_workers: 8
  train_epochs: 100
  patience: 20
  batch_size: 128
  learning_rate: 0.002
  lradj: cosine
  t_layer: 4
  v_layer: 0
  dropout: 0.1
  patch_len: 80
  patch_stride: 20
  augmentations: none
  channel_basis_dim: 32
  k_basis_dim: 16
  t_basis_dim: 16
  patch_embed_dim: 128
  use_channel_adapter: false
  canonical_channels: 32
  canonical_channel_coord_path: ./configs/electrodes/FACED_new.csv
  no_channel_prior: false
electrode_csv: ./configs/electrodes/FACED_new.csv
electrode_montage_used: standard_1020
electrode_channel_count: 32
